app:
  name: Josys-User-Profile-Handler
  host: localhost
  port: 3000
  node_env: development

error:
  sentry:
    enable: true
    log_level: error
    traces_sample_rate: 1.0
    debug_mode: false
